language: python
python: 3.6.7

env:
  - BOTO_CONFIG=/dev/null

install:
  - pip install pipenv

script:
  - pipenv install --dev
  - pipenv run coverage run --include=./redshells/* -m unittest discover -v -s ./test/

after_success:
  - coveralls