from redshells.contrib.train.train_feature_aggregation_similarity_model import TrainFeatureAggregationSimilarityModel
from redshells.contrib.train.train_graph_convolutional_matrix_completion import TrainGraphConvolutionalMatrixCompletion
from redshells.contrib.train.train_matrix_factorization import TrainMatrixFactorization
import redshells.train.utils
