name: YAPF Formatting Check

on:
    push:
        branches: [ master ]
    pull_request:


jobs:
  formatting-check:

    name: Formatting Check
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install toml yapf
    - name: run YAPF to test if python code is correctly formatted
      run: |
        yapf --diff --recursive --verbose $GITHUB_WORKSPACE
